POST http://localhost:3001/backend/heroes
Content-Type: application/json

{
    "name": "Ryu Hyeon Jin",
    "position": "P",
    "number": 99,
    "description": "The best Korean ballplayer around right now",
    "heroicScore": 99
}
